AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 600

Resources:
  UserTodoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes: ["*/*"]

  UserTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 203084879193.dkr.ecr.ap-south-1.amazonaws.com/todo-function:0.0.3
      Architectures:
        - x86_64
      Events:
        UserTodoFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref UserTodoApi
            Path: "/{proxy+}"
            Method: ANY
        UserTodoFunctionRoot:
          Type: Api
          Properties:
            RestApiId: !Ref UserTodoApi
            Path: "/"
            Method: ANY
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./todo
      Dockerfile: Dockerfile

Outputs:
  UserTodoFunctiondApi:
    Description: "API Gateway endpoint URL for dev stage for UserTodo function"
    Value: !Sub "https://${UserTodoApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  UserTodoFunction:
    Description: "UserTodo Lambda Function ARN"
    Value: !GetAtt UserTodoFunction.Arn
  UserTodoFunctionIamRole:
    Description: "Implicit IAM Role created for Todos function"
    Value: !GetAtt UserTodoFunctionRole.Arn
