AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "sam-app

  Sample SAM Template for sam-app

  "
Globals:
  Function:
    Timeout: 600

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes: ["*/*"]
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 414608916390.dkr.ecr.ap-south-1.amazonaws.com/user-auth-todo:0.0.3
      Architectures:
        - x86_64
      Events:
        UserFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: "/{proxy+}"
            Method: ANY
        UserFunctionRoot:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: "/"
            Method: ANY
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./auth
      Dockerfile: Dockerfile

Outputs:
  UserFunctiondApi:
    Description: "API Gateway endpoint URL for dev stage for User function"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/dev/api"
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: "Implicit IAM Role created for Users function"
    Value: !GetAtt UserFunctionRole.Arn
